version: '3.3'

services:

  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./public:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - app-network

  node:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    container_name: lawy_node
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: lawy_mongodb
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lawy
      - MONGO_INITDB_ROOT_PASSWORD=secret

networks:
  app-network:
    external: true
