version: '3.3'

services:

  node:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    container_name: lawy_node
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: lawy_mongodb
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lawy
      - MONGO_INITDB_ROOT_PASSWORD=secret

  mongoex:
    image: mongo-express
    environment:
        - ME_CONFIG_MONGODB_SERVER=mongo
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
        - ME_CONFIG_MONGODB_ADMINUSERNAME=lawy
        - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
        - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
        - ME_CONFIG_MONGODB_AUTH_USERNAME=lawy
        - ME_CONFIG_MONGODB_AUTH_PASSWORD=secret
        - ME_CONFIG_BASICAUTH_USERNAME=lawy
        - ME_CONFIG_BASICAUTH_PASSWORD=secret
    depends_on:
        - mongo
    networks:
      - app-network
    ports:
        - "8888:8081"
    restart: on-failure:10

  nginx:
      image: nginx:1.15-alpine
      ports:
        - "80:80"
      volumes:
        - ./data/nginx_dev:/etc/nginx/conf.d
        - ./webapp:/usr/share/nginx/html
      depends_on: 
        - node
      networks:
        - app-network

networks:
  app-network:
    driver: bridge
