version: '3.3'

services:

  node:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    container_name: lawy_node
    networks:
      - app-network
    ports:
      - 80:3030
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: lawy_mongodb
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lawy
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
    - './mongodb:/data/db'

networks:
  app-network:
    driver: bridge
